name: task_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  flutter_lints: ^3.0.0
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  path: ^1.9.0
  sqflite_common_ffi_web: ^0.4.4
  google_fonts: ^6.2.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/todo.png
